import React from 'react'
import { HashLink as Link } from 'react-router-hash-link'
import './assets/Test.css'

const Test = () => {
  return (
    <div className="pettyCashAccount">
      <h1 className="pettyCashAccount__title" style={{ textAlign: 'center' }}>
        ReactJS Editable Table
      </h1>
      <div className="manual" style={{ textAlign: 'left' }}>
        <h2>User Manual</h2>
        <h2>Signup</h2>
        <p>
          Signup is done at the <Link to="/Home/employee-user">employee/user</Link> page. The
          password is autogenerated and can be changed by the new user at the{' '}
          <Link to="/Home/settings">settings</Link> page.
        </p>
        <h2>Tables</h2>
        <p>There are two versions of the table:</p>
        <ol>
          <li>
            <strong>Lease Tab</strong>: This version uses modals for input.
          </li>
          <li>
            <strong>Employee Tab</strong>: This version uses dynamic input fields for user
            interaction.
          </li>
        </ol>
        <h2>Tax Overview</h2>
        <p>
          The Tax Overview page disables all user inputs for security reasons. Any changes to the
          tax information should be done at their original places.
        </p>
        <h2>Navigation</h2>
        <p>
          Use the navigation bar at the top of the page to move between different sections of the
          application.
        </p>
        <h2>Support</h2>
        <p>If you encounter any issues or have any questions, please contact our support team.</p>
      </div>
    </div>
  )
}

export default Test
